FROM python:3.12-slim

ENV PYTHONUNBUFFERED True
ENV PORT=8080

# Set PYTHONPATH to include the application directory
ENV PYTHONPATH=/usr/src/project/application


# set the working directory
WORKDIR /usr/src/project

# install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt



# copy application code
COPY ./application ./application

# Ensure the app listens on port 8080
EXPOSE 8080

# start the server
CMD ["uvicorn", "main_chatwoot:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers", "--log-level", "info"]
